using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public enum ChatNetworkBlobType
{
    NETBLOB_UNKNOWN = 0,
    NETBLOB_EVENT_BINARY = 1, // Server to client
    NETBLOB_EVENT_XMLRPC = 2,
    NETBLOB_REQUEST_BINARY = 3, // Client to server
    NETBLOB_REQUEST_XMLRPC = 4,
    NETBLOB_RESPONSE_BINARY = 5, // Server to client acknowledgement
    NETBLOB_RESPONSE_XMLRPC = 6,
    NETBLOB_PADDING = 0x7FFFFFFF
}

// AsyncMethod::AsyncMethodID
public enum AsyncMethodID
{
    ASYNCMETHOD_UNKNOWN=0,
    ASYNCMETHOD_SENDTOROOMBYNAME=1,
    ASYNCMETHOD_SENDTOROOMBYID=2,
    ASYNCMETHOD_CREATEROOM=3,
    ASYNCMETHOD_INVITECLIENTTOROOMBYID=4,
    ASYNCMETHOD_EJECTCLIENTFROMROOMBYID=5
}

public enum ChatEventType
{
    CHATEVENT_INVALID = 0,
    CHATEVENT_SENDTOROOM = 1,
    CHATEVENT_PROXYCREATECLIENT = 2,
    CHATEVENT_PROXYDESTROYCLIENT = 3,
    CHATEVENT_PROXYSQUELCH = 4,
    CHATEVENT_PROXYUNSQUELCH = 5,
    CHATEVENT_MIGRATECLIENT = 6,
    CHATEVENT_PROXYDESTROYCLIENTBYACCOUNTNAME = 7,
    CHATEVENT_PADDING = 0x7FFFFFFF
}
